USE [master]
GO
/****** Object:  Database [JWTDB]    Script Date: 3/9/2021 5:54:10 PM ******/
CREATE DATABASE [JWTDB]
 CONTAINMENT = NONE
 ON  PRIMARY     /****** Please change path to create mdf amd ldf file to apprprate locations ******/
( NAME = N'JWTDB', FILENAME = N'H:\JWTDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )  
 LOG ON 
( NAME = N'JWTDB_log', FILENAME = N'H:\JWTDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [JWTDB] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [JWTDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [JWTDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [JWTDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [JWTDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [JWTDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [JWTDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [JWTDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [JWTDB] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [JWTDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [JWTDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [JWTDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [JWTDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [JWTDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [JWTDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [JWTDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [JWTDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [JWTDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [JWTDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [JWTDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [JWTDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [JWTDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [JWTDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [JWTDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [JWTDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [JWTDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [JWTDB] SET  MULTI_USER 
GO
ALTER DATABASE [JWTDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [JWTDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [JWTDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [JWTDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [JWTDB]
GO
/****** Object:  Table [dbo].[ErrorLog]    Script Date: 3/9/2021 5:54:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ErrorLog](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Message] [varchar](max) NULL,
	[RequestMethod] [varchar](50) NULL,
	[RequestUri] [varchar](50) NULL,
	[TimeUtc] [datetime] NULL,
 CONSTRAINT [PK_ErrorLog] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[tblTask]    Script Date: 3/9/2021 5:54:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tblTask](
	[QuoteNumber] [int] IDENTITY(1,1) NOT NULL,
	[QuoteType] [varchar](50) NULL,
	[Contact] [varchar](50) NULL,
	[TaskDescription] [varchar](50) NULL,
	[TaskType] [varchar](50) NULL,
	[DueDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[QuoteNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[tblUser]    Script Date: 3/9/2021 5:54:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tblUser](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Username] [varchar](50) NULL,
	[Password] [varchar](50) NULL,
 CONSTRAINT [PK_tblUser] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
USE [master]
GO
ALTER DATABASE [JWTDB] SET  READ_WRITE 
GO
